-- 每天凌晨0零0分1秒时候，更新字段 score_today

CREATE EVENT `UPDATE_SCORE_TODAY`
ON SCHEDULE EVERY 1 DAY STARTS '2019-05-30 16:15:01'
ON COMPLETION NOT PRESERVE
ENABLE
DO
CALL UPDATE_USER_SCORE_TODAY();

create procedure UPDATE_USER_SCORE_TODAY()
BEGIN
  update users set score_today = 0;
END;